/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.BenefactorCompanyAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.FinanceOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import userinterface.FinancialManagerRole.*;
import Business.WorkQueue.DonationWorkRequest;
import Business.WorkQueue.Resource;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sushr
 */
public class ViewDonationJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
DonationWorkRequest dwr;
EcoSystem business;
Enterprise enterprise;
UserAccount account;
    /**
     * Creates new form ViewDonationJPanelF
     */
    public ViewDonationJPanel(JPanel userProcessContainer,DonationWorkRequest dwr,EcoSystem business,Enterprise e,UserAccount ua) {
        initComponents();
        this.setSize(1100,800);
        this.userProcessContainer=userProcessContainer;
        this.business=business;
        this.dwr=dwr;
        this.enterprise=e;
        this.account=ua;
        setEnabled();
        setValues();
        setDisabled();
        jTextAreaMessage.setEnabled(true);
        jTextAreaMessage.setText(dwr.getMessage());
        jTextAreaMessage.setEnabled(false);
        jTextFieldDonorCompany.setEnabled(true);
        jTextFieldDonorCompany.setText(dwr.getNgoName());
        jTextFieldDonorCompany.setEnabled(false);
    }

    private void populateResourceTable() {
        DefaultTableModel dtm = (DefaultTableModel) jTableResources.getModel();
        dtm.setRowCount(0);
        jTableResources.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        for (Resource r : dwr.getResourceList()) {
            Object[] row = new Object[2];
            row[0] = r;
            row[1] = r.getQuantity();
            dtm.addRow(row);
        }

    }
     private void setEnabled()
     {
         jButtonAddDonation.setEnabled(true);
         jButtonAddNewType.setEnabled(true);
         jComboBoxDonationType.setEnabled(true);
         jTextFieldDonationName.setEnabled(true);
         jTextFieldCreateDate.setEnabled(true);
         
     }
     private void setDisabled()
     {
         jTextFieldDonationName.setEnabled(false);
         jTextFieldCreateDate.setEnabled(false);
//         jTextAreaDesc.setEnabled(false);
//         jTextFieldDonorCompany.setEnabled(false);
         jButtonAddDonation.setEnabled(false);
         jButtonAddNewType.setEnabled(false);
         jComboBoxDonationType.setEnabled(false);
     }
    private void setValues()
    {
        jTextFieldDonationName.setText(dwr.getTitle());
        
        long m=dwr.getCreatedDate();
        Date d=new Date(m);
        jTextFieldCreateDate.setText(String.valueOf(d));
        
//        jTextAreaDesc.setText(dwr.getMessage());
        
        jTextFieldDonorCompany.setText(dwr.getEnterpriseName());
        
        
        populateTable();
    }
    private void populateTable()
    {
        DefaultTableModel dtm = (DefaultTableModel) jTableResources.getModel();
        dtm.setRowCount(0);
        jTableResources.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        for (Resource r : dwr.getResourceList()) {
            Object[] row = new Object[2];
            row[0] = r;
            row[1] = r.getQuantity();
            dtm.addRow(row);
        }

        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableResources = new javax.swing.JTable();
        jTextFieldDonationName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCreateDate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDonorCompany = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaMessage = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldNewType = new javax.swing.JTextField();
        jButtonAddNewType = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldAmount = new javax.swing.JTextField();
        jButtonAddDonation = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxDonationType = new javax.swing.JComboBox<>();
        jButtonUpdate = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableResources.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Resource", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableResources);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 560, 177));
        add(jTextFieldDonationName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 180, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Donation Name*:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("View Donation");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 32, -1, -1));
        add(jTextFieldCreateDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 90, 133, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Created Date:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, -1, -1));
        add(jTextFieldDonorCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 180, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Donation for:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, -1));

        backJButton.setBackground(new java.awt.Color(255, 255, 255));
        backJButton.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/IconsPictures/Icons/Back.GIF"))); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 28, -1, -1));

        jTextAreaMessage.setColumns(20);
        jTextAreaMessage.setRows(5);
        jScrollPane5.setViewportView(jTextAreaMessage);

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 380, 290, 170));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Remarks:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, -1, -1));
        add(jTextFieldNewType, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, 200, -1));

        jButtonAddNewType.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAddNewType.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jButtonAddNewType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/IconsPictures/Icons/Add.GIF"))); // NOI18N
        jButtonAddNewType.setText("Add");
        jButtonAddNewType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddNewTypeActionPerformed(evt);
            }
        });
        add(jButtonAddNewType, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 220, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("New Type:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, -1));
        add(jTextFieldAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 135, -1));

        jButtonAddDonation.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAddDonation.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jButtonAddDonation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/IconsPictures/Icons/Add.GIF"))); // NOI18N
        jButtonAddDonation.setText("Add");
        jButtonAddDonation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddDonationActionPerformed(evt);
            }
        });
        add(jButtonAddDonation, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 300, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Amount:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Donation Type:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jComboBoxDonationType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxDonationType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDonationTypeActionPerformed(evt);
            }
        });
        add(jComboBoxDonationType, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 180, -1));

        jButtonUpdate.setBackground(new java.awt.Color(255, 255, 255));
        jButtonUpdate.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jButtonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/IconsPictures/Icons/edit.GIF"))); // NOI18N
        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 710, -1, -1));

        jButtonSave.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSave.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/IconsPictures/Icons/save.GIF"))); // NOI18N
        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 710, 180, 60));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/BenefactorCompanyAdminRole/Blue.PNG"))); // NOI18N
        jLabel8.setText("jLabel8");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
                userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        FinancialManagerWorkAreaJPanel emwajp = (FinancialManagerWorkAreaJPanel) component;
        emwajp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

        // TODO add your handling code here:
    }//GEN-LAST:event_backJButtonActionPerformed

    private void jButtonAddNewTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddNewTypeActionPerformed

        if(jTextFieldNewType.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "New type can't be null");
        }
        else{
            for (Network n : business.getNetworkList()) {
                for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                    if (e.getName().equals(dwr.getEnterpriseName())) {
                        for(String s:e.getDonationType()){
                            if(s.equals(jTextFieldNewType.getText()))
                            {
                                JOptionPane.showMessageDialog(null, "Already exists");
                                return;

                            }

                        }
                        e.getDonationType().add(jTextFieldNewType.getText());
//                        populateComboBox();
                    }
                }
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddNewTypeActionPerformed

    private void jButtonAddDonationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddDonationActionPerformed
        boolean flag=true;
        if(!(Integer.parseInt(jTextFieldAmount.getText())>0))
        {
            JOptionPane.showMessageDialog(null, "Quantity should be more than 0");
        }
        else{
            for(Resource r:dwr.getResourceList())
            {
                flag=true;
                if(r.getResourceName().equals((String)dwr.getEnterpriseName()))
                {
                    //                    System.out.println("inside if");
                    flag=false;
                    int a=r.getQuantity();
                    int b=Integer.parseInt(jTextFieldAmount.getText());
                    r.setQuantity(a+b);
                    populateResourceTable();

                }
            }
            if(flag){
                Resource resource = new Resource();
                resource.setResourceName((String)jComboBoxDonationType.getSelectedItem());
                resource.setQuantity(Integer.parseInt(jTextFieldAmount.getText()));
                dwr.getResourceList().add(resource);
                populateResourceTable();}
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddDonationActionPerformed

    private void jComboBoxDonationTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDonationTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDonationTypeActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
setEnabled();
        jButtonUpdate.setEnabled(false);
        jButtonSave.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        dwr.setTitle(jTextFieldDonationName.getText());
        dwr.setSender(account);
        dwr.setStatus("New");
        dwr.setMessage("New Donation has been created");
//        dwr.setEnterpriseName(enterprise.getName());
        setDisabled();
        jButtonSave.setEnabled(false);
        jButtonUpdate.setEnabled(true);
        String sendTo=null;
        int count=0;
        for (Network n : business.getNetworkList()) {
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                if (e.getName().equals(dwr.getNgoName())) {
                    for (Organization o:e.getOrganizationDirectory().getOrganizationList()) {
                        {
                            if(o instanceof FinanceOrganization)
                            {
                                count=0;
                                for(UserAccount ua:o.getUserAccountDirectory().getUserAccountList())
                                {
                                    if(count==0){
                                    sendTo=ua.getEmail();
                                    count++;
                                    }
                                    else
                                    {
                                        String temp=sendTo+" ,"+ua.getEmail();
                                        sendTo=temp;
                                    }
                                }
                                
                            }
                            
                        }
                    }
                }
            }
        }
        
//      ****************************************** Email code ***************************
//            try{
//            emailclass.generateAndSendEmailDonation(sendTo,dwr);
//            }
//            catch(Exception e)
//            {
//                System.out.println(""+e);
//            }

        
        JOptionPane.showMessageDialog(null, "Record successfuly modified","Message",JOptionPane.INFORMATION_MESSAGE);
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton jButtonAddDonation;
    private javax.swing.JButton jButtonAddNewType;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<String> jComboBoxDonationType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTableResources;
    private javax.swing.JTextArea jTextAreaMessage;
    private javax.swing.JTextField jTextFieldAmount;
    private javax.swing.JTextField jTextFieldCreateDate;
    private javax.swing.JTextField jTextFieldDonationName;
    private javax.swing.JTextField jTextFieldDonorCompany;
    private javax.swing.JTextField jTextFieldNewType;
    // End of variables declaration//GEN-END:variables
}
