/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FinancialManagerRole;

import Business.Enterprise.Enterprise;
import Business.Organization.AdminOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FundsWorkRequest;
import Business.WorkQueue.Resource;
import Business.WorkQueue.WorkRequest;
import Business.emailclass;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author h
 */
public class BudgetJPanel extends javax.swing.JPanel {

    Enterprise enterprise;
    JPanel userProcessContainer;

    /**
     * Creates new form FinancialManagerWorkAreaJPanel
     */
    public BudgetJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.setSize(1100,800);
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        populateCombo();
        disableQuantityRelated();
    }
    private boolean validateFields()
    {
        int selectedRow=benefactorsTbl.getSelectedRow();
        Resource r=(Resource)benefactorsTbl.getValueAt(selectedRow,0);
        
        int newQ=Integer.parseInt(jTextFieldNewQty.getText());
        if (selectedRow<0){
            JOptionPane.showMessageDialog(null,"Please select a row from the table first to view details","Warning",JOptionPane.WARNING_MESSAGE);
            return false;
        }
        else if(jTextAreaRemarks.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Remarks cannot be kept blank","Warning",JOptionPane.WARNING_MESSAGE);
            return false;
        }
        else if(newQ>r.getQuantity())
        {
            JOptionPane.showMessageDialog(null,"New Quantity cant be greater","Warning",JOptionPane.WARNING_MESSAGE);
            return false;
        }
        else{
        return true;
        }
    }

    private void disableQuantityRelated()
    {
        jButtonSubmit.setVisible(false);
        jTextAreaRemarks.setVisible(false);
        jLabel1.setVisible(false);
        jTextFieldNewQty.setVisible(false);
        jLabel2.setVisible(false);
        
    }
    
    private void enableQuantityRelated()
    {
        jTextFieldNewQty.setVisible(true);
        jButtonSubmit.setVisible(true);
        jTextAreaRemarks.setVisible(true);
        jLabel1.setVisible(true);
        jLabel2.setVisible(true);
        
    }
    
    
    private void populateCombo() {
        jComboBoxDonationType.removeAllItems();
        for (String s : enterprise.getDonationType()) {
            jComboBoxDonationType.addItem(s);

        }

    }

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) benefactorsTbl.getModel();
        dtm.setRowCount(0);
        int count=0;
        benefactorsTbl.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        for (WorkRequest wr : enterprise.getWorkQueue().getWorkRequestList()) {
//            System.out.println(""+wr.getMessage());
//            System.out.println(""+wr.);
            if (wr instanceof FundsWorkRequest) {
                FundsWorkRequest fwr = (FundsWorkRequest) wr;
                for (Resource r : fwr.getDonationList()) {
//                    System.out.println(""+r.getResourceName());
//                    System.out.println(""+r.getQuantity());
                    String b=(String)jComboBoxDonationType.getSelectedItem();
                    System.out.println(""+b);
                    if ( b!=null && (b.equals(r.getResourceName())) &&r.getQuantity()>0  ) {

                        Object[] row = new Object[3];
                        row[0] = r;
                        row[1] = fwr.getBenefactorName();
                        row[2]= r.getQuantity();
                        dtm.addRow(row);
                        count+=r.getQuantity();
                        

                    }
                }
            }
        }
        totalBudgetTextField.setEnabled(true);
        totalBudgetTextField.setText(String.valueOf(count));
        totalBudgetTextField.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        benefactorsTbl = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonChangeQty = new javax.swing.JButton();
        totalBudgetTextField = new javax.swing.JTextField();
        jComboBoxDonationType = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaRemarks = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNewQty = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonSubmit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/IconsPictures/Icons/Back.GIF"))); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        benefactorsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Resource", "Benefactor Name", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(benefactorsTbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 247, 593, 198));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Budget Screen");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 28, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total Amount :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, -1, -1));

        jButtonChangeQty.setBackground(new java.awt.Color(255, 255, 255));
        jButtonChangeQty.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jButtonChangeQty.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/IconsPictures/Icons/edit.GIF"))); // NOI18N
        jButtonChangeQty.setText("Change Qty");
        jButtonChangeQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeQtyActionPerformed(evt);
            }
        });
        add(jButtonChangeQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(745, 289, -1, -1));

        totalBudgetTextField.setEnabled(false);
        add(totalBudgetTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, 170, -1));

        jComboBoxDonationType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxDonationType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDonationTypeActionPerformed(evt);
            }
        });
        add(jComboBoxDonationType, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 230, -1));

        jTextAreaRemarks.setColumns(20);
        jTextAreaRemarks.setRows(5);
        jScrollPane2.setViewportView(jTextAreaRemarks);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 580, 670, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Remarks:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, -1, -1));
        add(jTextFieldNewQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 480, 190, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("New Amount:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, -1, -1));

        jButtonSubmit.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSubmit.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jButtonSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/IconsPictures/Icons/Add.GIF"))); // NOI18N
        jButtonSubmit.setText("Submit");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });
        add(jButtonSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 721, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/IconsPictures/Purple.PNG"))); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        FinancialManagerWorkAreaJPanel emwajp = (FinancialManagerWorkAreaJPanel) component;
        emwajp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void jButtonChangeQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeQtyActionPerformed
int selectedRow=benefactorsTbl.getSelectedRow();
        if (selectedRow<0){
            JOptionPane.showMessageDialog(null,"Please select a row from the table first to view details","Warning",JOptionPane.WARNING_MESSAGE);
        }
        
        else
        {
            enableQuantityRelated();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonChangeQtyActionPerformed

    private void jComboBoxDonationTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDonationTypeActionPerformed
        populateTable();

// TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDonationTypeActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        
        if(validateFields())
{
    int selectedRow = benefactorsTbl.getSelectedRow();
    Resource r=(Resource)benefactorsTbl.getValueAt(selectedRow,0);
    int q=Integer.parseInt(jTextFieldNewQty.getText());
    int p=r.getQuantity();
    int c=p-q;
    r.setQuantity(c);
    populateTable();
    disableQuantityRelated();
String sendTo=null;
        int count=0;
        
                    for (Organization o:enterprise.getOrganizationDirectory().getOrganizationList()) {
                        {
                            if(o instanceof AdminOrganization)
                            {
                                count=0;
                                for(UserAccount ua:o.getUserAccountDirectory().getUserAccountList())
                                {
                                    if(count==0){
                                    sendTo=ua.getEmail();
                                    count++;
                                    }
                                    else
                                    {
                                        String temp=sendTo+" ,"+ua.getEmail();
                                        sendTo=temp;
                                    }
                                }
                                
                            }
                            
                        }
                    }
         
                    System.out.println(""+sendTo);
//      ****************************************** Email code ***************************
            try{
            emailclass.generateAndSendEmailResource(sendTo,r);
            }
            catch(Exception e)
            {
                System.out.println(""+e);
            }

   jTextAreaRemarks.setText("");
        jTextFieldNewQty.setText("");
 

}


        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTable benefactorsTbl;
    private javax.swing.JButton jButtonChangeQty;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JComboBox<String> jComboBoxDonationType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaRemarks;
    private javax.swing.JTextField jTextFieldNewQty;
    private javax.swing.JTextField totalBudgetTextField;
    // End of variables declaration//GEN-END:variables
}
