package userinterface.FinancialManagerRole;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.WishWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Hanan
 */
public class ViewWishJPanelF extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccount ua;
    WishWorkRequest wr;
    /**
     * Creates new form WishJPanel
     */
    public ViewWishJPanelF(JPanel userProcessContainer, WishWorkRequest wr,UserAccount ua) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.setSize(1100,800);
        this.wr=wr;
        this.ua=ua;
        enableFields();
        setValues();
        disableFields();
        jButtonSave.setEnabled(false);
        
    }
    
    private void enableFields()
    {
        jTextFieldCost.setEnabled(true);
        jTextFieldWishTitle.setEnabled(true);
        jDateChooserRequiredDate.setEnabled(true);
        textAreaWishDesc.setEnabled(true);
        textAreaWisherDetails.setEnabled(true);
        
    }
    private void setValues()
    {
        
        long millis = wr.getRequiredDate();
        Date d = new Date(millis);
        jTextFieldCost.setText(String.valueOf(wr.getCost()));
        jTextFieldWishTitle.setText(wr.getWishTitle());
        jDateChooserRequiredDate.setDate(d);
        textAreaWishDesc.setText(wr.getWishDesc());
        textAreaWisherDetails.setText(wr.getWishDetails());
        
    }
    private void disableFields()
    {
        jTextFieldCost.setEnabled(false);
        jTextFieldWishTitle.setEnabled(false);
        jDateChooserRequiredDate.setEnabled(false);
        textAreaWishDesc.setEnabled(false);
        textAreaWisherDetails.setEnabled(false);
    }
    
        private boolean validateData()
    {
        if(!(jTextFieldWishTitle.getText().trim().length() > 0)){
           JOptionPane.showMessageDialog(null,"Wish Title field is empty","Warning",JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        else if(!isNumber(jTextFieldCost.getText().trim())){
           JOptionPane.showMessageDialog(null,"Cost field is non numeric","Warning",JOptionPane.WARNING_MESSAGE);
            return false;
        }
         else if(!(textAreaWishDesc.getText().trim().length() > 0)){
           JOptionPane.showMessageDialog(null,"Wish Description field is empty","Warning",JOptionPane.WARNING_MESSAGE);
            return false;
        }
          else if(!(textAreaWisherDetails.getText().trim().length()>0)){
           JOptionPane.showMessageDialog(null,"Wisher Details field is empty","Warning",JOptionPane.WARNING_MESSAGE);
            return false;
        }

        else{
          return true;  
        }
        
    }
    private boolean validateDate()
    {
        Date date=new Date();
        long i = date.getTime()+86400000;//this gets todays date and adds 24 hours in it     
        Date reqdDate = jDateChooserRequiredDate.getDate();
        long j = reqdDate.getTime();

        if(j<i)// we are checking requested date is greater than todays date by 24 hours     
        {
            JOptionPane.showMessageDialog(null, "Requested/Required date should be atleast 48 hours more than todays date");//copy me
            return false;
        }
        else
        {
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        remarksTextArea = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jButtonUpdate = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        textAreaWishDesc = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        Cost1 = new javax.swing.JLabel();
        jTextFieldCost = new javax.swing.JTextField();
        jDateChooserRequiredDate = new com.toedter.calendar.JDateChooser();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaWisherDetails = new javax.swing.JTextArea();
        Cost = new javax.swing.JLabel();
        jTextFieldWishTitle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bacjJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        remarksTextArea.setColumns(20);
        remarksTextArea.setRows(5);
        jScrollPane2.setViewportView(remarksTextArea);

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Viewing Wish");
        jLabel9.setToolTipText("");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 28, 270, 37));

        jButtonUpdate.setBackground(new java.awt.Color(255, 255, 255));
        jButtonUpdate.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jButtonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/IconsPictures/Icons/edit.GIF"))); // NOI18N
        jButtonUpdate.setText("Modify");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 700, -1, 70));

        jButtonSave.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSave.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/IconsPictures/Icons/save.GIF"))); // NOI18N
        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 700, -1, 70));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Required Date");
        jLabel4.setToolTipText("");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 251, -1, -1));

        jScrollPane4.setToolTipText("");

        textAreaWishDesc.setColumns(20);
        textAreaWishDesc.setRows(5);
        jScrollPane4.setViewportView(textAreaWishDesc);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 365, 491, 114));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Wish Description:");
        jLabel7.setToolTipText("");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 374, -1, -1));

        Cost1.setForeground(new java.awt.Color(255, 255, 255));
        Cost1.setText("Wisher Details:");
        Cost1.setToolTipText("");
        add(Cost1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 519, -1, -1));

        jTextFieldCost.setToolTipText("");
        add(jTextFieldCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(721, 290, 100, -1));

        jDateChooserRequiredDate.setToolTipText("");
        add(jDateChooserRequiredDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 251, -1, -1));

        jScrollPane3.setToolTipText("");

        textAreaWisherDetails.setColumns(20);
        textAreaWisherDetails.setRows(5);
        jScrollPane3.setViewportView(textAreaWisherDetails);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 519, 491, 114));

        Cost.setForeground(new java.awt.Color(255, 255, 255));
        Cost.setText("Cost:");
        Cost.setToolTipText("");
        add(Cost, new org.netbeans.lib.awtextra.AbsoluteConstraints(641, 290, -1, -1));

        jTextFieldWishTitle.setToolTipText("");
        add(jTextFieldWishTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 125, 183, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Wish Title:");
        jLabel2.setToolTipText("");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 128, -1, -1));

        bacjJButton.setBackground(new java.awt.Color(255, 255, 255));
        bacjJButton.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        bacjJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/IconsPictures/Icons/Back.GIF"))); // NOI18N
        bacjJButton.setText("Back");
        bacjJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bacjJButtonActionPerformed(evt);
            }
        });
        add(bacjJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 28, -1, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/IconsPictures/Purple.PNG"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        if(validateData() && validateDate()){
        wr.setSender(ua);
        wr.setMessage("Cost has been determined for a wish");
        wr.setStatus("Posted");
        wr.setCost(Integer.parseInt(jTextFieldCost.getText()));
        wr.setWishTitle(jTextFieldWishTitle.getText());
        wr.setWishDesc(textAreaWishDesc.getText());
        wr.setWishDetails(textAreaWisherDetails.getText());
        Date d = jDateChooserRequiredDate.getDate();
        long m = d.getTime();
        wr.setRequiredDate(m);
        disableFields();
        jButtonSave.setEnabled(false);
        jButtonSave.setEnabled(true);
        JOptionPane.showMessageDialog(null, "Record successfuly modified","Message",JOptionPane.INFORMATION_MESSAGE);        

        // TODO add your handling code here:
        }
        else
            return;
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        enableFields();
        jButtonUpdate.setEnabled(false);
        jButtonSave.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void bacjJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bacjJButtonActionPerformed
         userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        FinancialManagerWorkAreaJPanel tcwajp = (FinancialManagerWorkAreaJPanel) component;
        tcwajp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_bacjJButtonActionPerformed
        private boolean isNumber(String str) {
        int num;
        try{
            num = Integer.parseInt(str);
            
        } catch (NumberFormatException nfe){
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cost;
    private javax.swing.JLabel Cost1;
    private javax.swing.JButton bacjJButton;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonUpdate;
    private com.toedter.calendar.JDateChooser jDateChooserRequiredDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextFieldCost;
    private javax.swing.JTextField jTextFieldWishTitle;
    private javax.swing.JTextArea remarksTextArea;
    private javax.swing.JTextArea textAreaWishDesc;
    private javax.swing.JTextArea textAreaWisherDetails;
    // End of variables declaration//GEN-END:variables
}
