/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HumanResourceManagerRole;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.VolunteerOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EventWorkRequest;
import Business.WorkQueue.VolunteerWork;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sneha
 */
public class AllocateResources extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccount ua;
    EventWorkRequest wr;
    Enterprise enterprise;

    /**
     * Creates new form ManageVolunteersWorkArea
     */
    public AllocateResources(JPanel userProcessContainer, EventWorkRequest wr, UserAccount ua, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.wr = wr;
        this.ua = ua;
        this.enterprise = enterprise;
        jLabel4.setText(wr.getEventName());
        jTextFieldTotalNeeded.setText(String.valueOf(wr.getVolunteers()));
        jTextFieldTotalNeeded.setEnabled(false);
        jTextFieldTotalAssigned.setEnabled(false);
        populateAssignedVolunteers();
    }

    private boolean checkLimit()
    {
        jTextFieldTotalAssigned.setEnabled(true);
        jTextFieldTotalNeeded.setEnabled(true);
        
        String a=jTextFieldTotalAssigned.getText();
        String b=jTextFieldTotalNeeded.getText();
//        System.out.println("A>>>>>>>>>"+a+"B>>>>>>>>>>"+b);
jTextFieldTotalAssigned.setEnabled(false);
        jTextFieldTotalNeeded.setEnabled(false);
        if(a.equals(b))
        {
            return true;
            
        }
        else 
            return false;
    }
    
    private void populateAssignedVolunteers() {
        DefaultTableModel dtm = (DefaultTableModel) jTableAssigned.getModel();
        dtm.setRowCount(0);
        int count = 0;
        
        for (VolunteerWork v : wr.getVolunteerList()) {

            Object[] o = new Object[3];
            o[0] = v;
            o[1] = v.getUserName();
            o[2] = v.getSkills();
            dtm.addRow(o);
            count++;
        
        }
        jTextFieldTotalAssigned.setEnabled(true);
        jTextFieldTotalAssigned.setText(String.valueOf(count));
        jTextFieldTotalAssigned.setEnabled(false);
        
        
        populateUnassignedVolunteers();
        
    }

    private void populateUnassignedVolunteers() {
        DefaultTableModel dtm = (DefaultTableModel) JTableAvailable.getModel();
        dtm.setRowCount(0);
        boolean flag = true;
        for (Organization o : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (o instanceof VolunteerOrganization) {
                for (UserAccount ua : o.getUserAccountDirectory().getUserAccountList()) {
                    flag = true;
                    for (VolunteerWork v : wr.getVolunteerList()) {
                        if (v.getName().equals(ua.getName())) {
                            flag = false;
                        }

                    }
                    if (flag) {
                        Object[] row = new Object[3];
                        row[0] = ua;
                        row[1] = ua.getName();
                        row[2] = ua.getSkillSet();
                        dtm.addRow(row);

                    }

                }

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTableAvailable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAssigned = new javax.swing.JTable();
        jButtonAdd = new javax.swing.JButton();
        jButtonRemove = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldTotalNeeded = new javax.swing.JTextField();
        jTextFieldTotalAssigned = new javax.swing.JTextField();

        JTableAvailable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UserName", "Name", "skill"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTableAvailable);
        if (JTableAvailable.getColumnModel().getColumnCount() > 0) {
            JTableAvailable.getColumnModel().getColumn(0).setResizable(false);
            JTableAvailable.getColumnModel().getColumn(1).setResizable(false);
            JTableAvailable.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel1.setText("Manage Volunteers");

        jLabel2.setText("Available Volunteers");

        jLabel3.setText("Event Name :");

        jLabel5.setText("Assigned Volunteers");

        jTableAssigned.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UserName", "Name", "Skill"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableAssigned);
        if (jTableAssigned.getColumnModel().getColumnCount() > 0) {
            jTableAssigned.getColumnModel().getColumn(0).setResizable(false);
            jTableAssigned.getColumnModel().getColumn(1).setResizable(false);
            jTableAssigned.getColumnModel().getColumn(2).setResizable(false);
        }

        jButtonAdd.setText(">>");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonRemove.setText("<<");
        jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveActionPerformed(evt);
            }
        });

        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Total Needed");

        jLabel8.setText("Total Assigned");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backJButton)
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldTotalNeeded, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldTotalAssigned, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(51, 51, 51)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(53, 53, 53)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButtonAdd)
                                        .addComponent(jButtonRemove)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(87, 87, 87)
                                    .addComponent(jLabel2)))
                            .addGap(41, 41, 41)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backJButton)
                    .addComponent(jLabel1))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldTotalNeeded, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jButtonAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonRemove)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTotalAssigned, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(33, 33, 33)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:userProcessContainer.remove(this);
        boolean b=checkLimit();
        if(b){
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        HumanResourceManagerWorkAreaJPanel emwajp = (HumanResourceManagerWorkAreaJPanel) component;
        emwajp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);}
        else
        {
            JOptionPane.showMessageDialog(null,"Check total needed and total assigned volunteers");
        }


    }//GEN-LAST:event_backJButtonActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        int selectedRow = JTableAvailable.getSelectedRow();
        if (selectedRow >= 0) {
            
                UserAccount ua = (UserAccount) JTableAvailable.getValueAt(selectedRow, 0);
                VolunteerWork v = new VolunteerWork();
                wr.getVolunteerList().add(v);
                v.setName(ua.getName());
                v.setSkills(ua.getSkillSet());
                v.setUserName(ua.getUsername());
                populateAssignedVolunteers();
            
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row from table first", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        boolean b = checkLimit();
        if(b)
        {
            
            for (Organization o : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (o instanceof VolunteerOrganization) {
                    for (UserAccount ua : o.getUserAccountDirectory().getUserAccountList()) {
                        for (VolunteerWork vw : wr.getVolunteerList()) {
                            if (vw.getUserName().equals(ua.getUsername())) {
                                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                                Date d = new Date(wr.getEventDate());
                                String dateVariable = sdf.format(d);
                                ua.getEventDatesList().add(dateVariable);
                            }
                        }
                    }
                }

            }
            wr.setStatus("Planned");
            enterprise.getEventList().add(wr);
            ua.getWorkQueue().getWorkRequestList().add(wr);
            JOptionPane.showMessageDialog(null,"Volunteers have been added to the event");
            backJButton.doClick();
            
        }
            else
        {
            JOptionPane.showMessageDialog(null,"Check total needed and total assigned volunteers");
            
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveActionPerformed
                int selectedRow = jTableAssigned.getSelectedRow();
        if (selectedRow >= 0) {
            
                VolunteerWork ua = (VolunteerWork) jTableAssigned.getValueAt(selectedRow, 0);
                
                wr.getVolunteerList().remove(ua);
                
                populateAssignedVolunteers();
            
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row from table first", "Warning", JOptionPane.WARNING_MESSAGE);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRemoveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableAvailable;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAssigned;
    private javax.swing.JTextField jTextFieldTotalAssigned;
    private javax.swing.JTextField jTextFieldTotalNeeded;
    // End of variables declaration//GEN-END:variables
}
