/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Analytics;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseRelation;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.WorkQueue.DonationWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author sneha
 */
public class CompanyFundComparison extends javax.swing.JPanel {

    JPanel userProcessContainer;
    EcoSystem business;
    Enterprise enterprise;
    ArrayList<Enterprise> enterpriseL;

    /**
     * Creates new form FundComparison
     */
    public CompanyFundComparison(JPanel userProcessContainer, EcoSystem business, Enterprise enterprise) {
        initComponents();
        populateJCombobox();
        this.enterprise = enterprise;
        this.business = business;
        this.userProcessContainer = userProcessContainer;
        enterpriseL = new ArrayList<Enterprise>();
        populateJCombobox();
        
        
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) companyJTable.getModel();

        model.setRowCount(0);
        for(Enterprise e:enterpriseL)
        {
            Object[] row = new Object[1];
            row[0]=e;
            
        
            
        }

    }

    public void populateJCombobox() {

        companyListJComboBox.removeAllItems();
        for (EnterpriseRelation er : enterprise.getEnterpriseRelationDirectory().getRelationList()) {
            if (er.getCompanyType().equals("Benefactor")) {
//                
//                String companyName = er.getCompanyName();
                for (Network n : business.getNetworkList()) {
                    for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                        if (e.getName().equals(er.getCompanyName())) {
                            companyListJComboBox.addItem(e);
                        }

                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        companyListJComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        addJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        companyJTable = new javax.swing.JTable();
        viewChartJButton = new javax.swing.JButton();

        companyListJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Benefactor Company");

        addJButton.setText("Add");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });

        companyJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Company Name "
            }
        ));
        jScrollPane1.setViewportView(companyJTable);

        viewChartJButton.setText("View Chart");
        viewChartJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewChartJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(61, 61, 61)
                        .addComponent(companyListJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(290, 290, 290)
                        .addComponent(addJButton)))
                .addContainerGap(257, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewChartJButton)
                .addGap(477, 477, 477))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(companyListJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(addJButton))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(viewChartJButton)
                .addGap(53, 53, 53))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
        // TODO add your handling code here:
        boolean flag=true;
        Enterprise enter=(Enterprise)companyListJComboBox.getSelectedItem();
        for(Enterprise e:enterpriseL)
        {
            if(e.getName().equals(enter.getName())){
                flag=false;
                JOptionPane.showMessageDialog(null, "Already Exists");
                break;
            }
            
            
        }
        if(flag)
        { 
            enterpriseL.add(enter);
        }
            
        
            
        
    
            
        
        populateTable();

    }//GEN-LAST:event_addJButtonActionPerformed

    private void viewChartJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewChartJButtonActionPerformed
        // TODO add your handling code here:
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for (Enterprise enterprise : enterpriseL) {
            for(WorkRequest wr:enterprise.getWorkQueue().getWorkRequestList())
            {
                if(wr instanceof DonationWorkRequest)
                {
//                 dataset.setValue(0, "Number of People", "Very High Risk");   
                }
            }
                
            }
//            dataset.setValue(countFemaleVeryHighRisk + countMaleVeryHighRisk, "Number of People", "Very High Risk");
    }//GEN-LAST:event_viewChartJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JTable companyJTable;
    private javax.swing.JComboBox companyListJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewChartJButton;
    // End of variables declaration//GEN-END:variables
}
