package userinterface.TargetCompanyAdminRole;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.WishWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Hanan
 */
public class ViewWishJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccount ua;
    WishWorkRequest wr;
    /**
     * Creates new form WishJPanel
     */
    public ViewWishJPanel(JPanel userProcessContainer, WishWorkRequest wr,UserAccount ua) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.wr=wr;
        this.ua=ua;
        enableFields();
        setValues();
        disableFields();
        jButtonSave.setEnabled(false);
        jTextAreaMessage.setEnabled(true);
        jTextAreaMessage.setText(wr.getMessage());
        jTextAreaMessage.setEnabled(false);
        
    }
    
    private void enableFields()
    {
        jTextFieldCost.setEnabled(true);
        jTextFieldWishTitle.setEnabled(true);
        jDateChooserRequiredDate.setEnabled(true);
        textAreaWishDesc.setEnabled(true);
        textAreaWisherDetails.setEnabled(true);
        
    }
    private void setValues()
    {
        
        long millis = wr.getRequiredDate();
        Date d = new Date(millis);
        jTextFieldCost.setText(String.valueOf(wr.getCost()));
        jTextFieldWishTitle.setText(wr.getWishTitle());
        jDateChooserRequiredDate.setDate(d);
        textAreaWishDesc.setText(wr.getWishDesc());
        textAreaWisherDetails.setText(wr.getWishDetails());
        
    }
    private void disableFields()
    {
        jTextFieldCost.setEnabled(false);
        jTextFieldWishTitle.setEnabled(false);
        jDateChooserRequiredDate.setEnabled(false);
        textAreaWishDesc.setEnabled(false);
        textAreaWisherDetails.setEnabled(false);
    }
    
             
    private boolean validateData()
    {
        if(!(jTextFieldWishTitle.getText().trim().length() > 0)){
           JOptionPane.showMessageDialog(null,"Wish Title field is empty","Warning",JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        else if(!isNumber(jTextFieldCost.getText().trim())){
           JOptionPane.showMessageDialog(null,"Cost field is non numeric","Warning",JOptionPane.WARNING_MESSAGE);
            return false;
        }
         else if(!(textAreaWishDesc.getText().trim().length() > 0)){
           JOptionPane.showMessageDialog(null,"Wish Description field is empty","Warning",JOptionPane.WARNING_MESSAGE);
            return false;
        }
          else if(!(textAreaWisherDetails.getText().trim().length()>0)){
           JOptionPane.showMessageDialog(null,"Wisher Details field is empty","Warning",JOptionPane.WARNING_MESSAGE);
            return false;
        }

        else{
          return true;  
        }
        
    }
    private boolean validateDate()
    {
        Date date=new Date();
        long i = date.getTime()+86400000;//this gets todays date and adds 24 hours in it     
        Date reqdDate = jDateChooserRequiredDate.getDate();
        long j = reqdDate.getTime();

        if(j<i)// we are checking requested date is greater than todays date by 24 hours     
        {
            JOptionPane.showMessageDialog(null, "Requested/Required date should be atleast 24 hours more than todays date");//copy me
            return false;
        }
        else
        {
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        remarksTextArea = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jButtonUpdate = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        textAreaWishDesc = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        Cost1 = new javax.swing.JLabel();
        jTextFieldCost = new javax.swing.JTextField();
        jDateChooserRequiredDate = new com.toedter.calendar.JDateChooser();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaWisherDetails = new javax.swing.JTextArea();
        Cost = new javax.swing.JLabel();
        jTextFieldWishTitle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bacjJButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaMessage = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();

        remarksTextArea.setColumns(20);
        remarksTextArea.setRows(5);
        jScrollPane2.setViewportView(remarksTextArea);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Viewing Wish");
        jLabel9.setToolTipText("");

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jLabel4.setText("Required Date");
        jLabel4.setToolTipText("");

        jScrollPane4.setToolTipText("");

        textAreaWishDesc.setColumns(20);
        textAreaWishDesc.setRows(5);
        jScrollPane4.setViewportView(textAreaWishDesc);

        jLabel7.setText("Wish Description:");
        jLabel7.setToolTipText("");

        Cost1.setText("Wisher Details:");
        Cost1.setToolTipText("");

        jTextFieldCost.setToolTipText("");

        jDateChooserRequiredDate.setToolTipText("");

        jScrollPane3.setToolTipText("");

        textAreaWisherDetails.setColumns(20);
        textAreaWisherDetails.setRows(5);
        jScrollPane3.setViewportView(textAreaWisherDetails);

        Cost.setText("Cost:");
        Cost.setToolTipText("");

        jTextFieldWishTitle.setToolTipText("");

        jLabel2.setText("Wish Title:");
        jLabel2.setToolTipText("");

        bacjJButton.setText("<< Back");
        bacjJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bacjJButtonActionPerformed(evt);
            }
        });

        jTextAreaMessage.setColumns(20);
        jTextAreaMessage.setRows(5);
        jScrollPane5.setViewportView(jTextAreaMessage);

        jLabel15.setText("Remarks");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bacjJButton)
                        .addGap(280, 280, 280)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jButtonUpdate)
                        .addGap(144, 144, 144)
                        .addComponent(jButtonSave))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel2)
                                        .addGap(30, 30, 30))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldWishTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(Cost))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jDateChooserRequiredDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 309, Short.MAX_VALUE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldCost, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Cost1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(27, 27, 27)
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bacjJButton))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldWishTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cost)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jDateChooserRequiredDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(112, 112, 112))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cost1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel15)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUpdate)
                    .addComponent(jButtonSave))
                .addGap(107, 107, 107))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        
        if(validateData() && validateDate()){
        wr.setCost(Integer.parseInt(jTextFieldCost.getText()));
        wr.setWishTitle(jTextFieldWishTitle.getText());
        wr.setWishDesc(textAreaWishDesc.getText());
        wr.setWishDetails(textAreaWisherDetails.getText());
        Date d = jDateChooserRequiredDate.getDate();
        long m = d.getTime();
        wr.setRequiredDate(m);
        disableFields();
        jButtonSave.setEnabled(false);
        jButtonUpdate.setEnabled(true);
        JOptionPane.showMessageDialog(null, "Record successfuly modified","Message",JOptionPane.INFORMATION_MESSAGE); 
        }
        else
            return;

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        enableFields();
        jButtonUpdate.setEnabled(false);
        jButtonSave.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void bacjJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bacjJButtonActionPerformed
         userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        TargetCompanyWorkAreaJPanel tcwajp = (TargetCompanyWorkAreaJPanel) component;
        tcwajp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_bacjJButtonActionPerformed


        private boolean isNumber(String str) {
        int num;
        try{
            num = Integer.parseInt(str);
            
        } catch (NumberFormatException nfe){
            return false;
        }
        return true;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cost;
    private javax.swing.JLabel Cost1;
    private javax.swing.JButton bacjJButton;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonUpdate;
    private com.toedter.calendar.JDateChooser jDateChooserRequiredDate;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextAreaMessage;
    private javax.swing.JTextField jTextFieldCost;
    private javax.swing.JTextField jTextFieldWishTitle;
    private javax.swing.JTextArea remarksTextArea;
    private javax.swing.JTextArea textAreaWishDesc;
    private javax.swing.JTextArea textAreaWisherDetails;
    // End of variables declaration//GEN-END:variables
}
